echo Extracting TUM_xyz...
./external/superpoint/extract_superpoint.py data/datasets/tum_xyz/rgb data/datasets/tum_xyz/superpoint/ --W 640 --H 480 --weights_path external/superpoint/superpoint_v1.pth
echo Extracting TUM_desk...
./external/superpoint/extract_superpoint.py data/datasets/tum_desk/rgb data/datasets/tum_desk/superpoint/ --W 640 --H 480 --weights_path external/superpoint/superpoint_v1.pth
